#!/bin/bash
# File:this script tells the story of  12-tell_the_story_of_passwd

while IFS=: read -r username password userid groupid info home shell; do
  echo "The user $username is part of the $groupid gang, lives in $home and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
