#!/usr/bin/env bash
# This script displays all currently running processes in a user-oriented format with hierarchy

ps -eo user,lstart,cmd --forest --header | awk 'BEGIN {print "USER STARTED CMD"} NR>1'
