#!/usr/bin/env bash
# This script displays all currently running processes for all users
# in a user-oriented format and shows process hierarchy

ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,cmd --forest
