#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

# Find the PID of the running 4-to_infinity_and_beyond process
pid=$(pgrep -f 4-to_infinity_and_beyond)

# Check if the process exists and kill it
if [[ -n $pid ]]; then
    kill "$pid"
    echo "Terminated"
else
    echo "No process found"
fi
